[build]
  command = "npm run build"
  publish = "dist/Zyphboard"

[context.production.environment]
  NETLIFY_SITE_URL = ""

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true